name: maru_naam_che_pathshala_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  velocity_x: ^4.2.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  flutter_inappwebview: ^6.0.0-beta.22
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
