name: maru_naam_che_pathshala_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  velocity_x: ^4.2.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  flutter_inappwebview: ^6.0.0-beta.22
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.4
  image_gallery_saver: ^2.0.3
  audioplayers: ^5.2.1
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^9.2.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
